travis:
  secure:
    BINSTAR_TOKEN: GSynmo0AgxaaH9K2cGksSevzHCmsPYdgVIItReG1Fk5krIRBjUZqbLJ5lWH86VFEGHCOo6uCLt1DLUuqzbAdRRLcowux1tYGWZSf9a4TTMociIz4FDb+AMqHZrBknUTvnOPQiJTxt19T/xHtNBrYPll4VLgLx3xKVJ8Vm+7QhE8RsYOoa6BfV8ARS87OdIMefjeYnsaqwUl65r59HXcOtiJOy/X2nu0TnPHGqI463XW+EuItkBrDabXOpqr97cLEA29cingXn2IP0aS2QkBYvQBsvJVQv4GMnvozVAPjSGkzJQwdaB456JS+oId9p61hmo25wZSkzu4Ks8sfCdyfDNYDE3pAmBlcz8qcKTwjTKUaKFOdrAzaxC844o81yivaHIVtNjtNBo2k6orZe5cYSUvab9d70ounwZb3YIeaAppaaNQ0/B5MJiTn676jcVxru3AaCuyC/gM7dgLRu5ZSfeoIhjjhMyUFl2MiIzxtT6yBb/aLSMtNLziQvXZYoVYE5rEO5wrilkgOfeUYOFUJcFUylpT1fsbnXBJJ3gH1lEtTtJRhgMbME0MNK5cdc86zmXaAE1dnpYEeyhqMOL2Su94LoVl58b+cxOoQpQjg+8TGgo3u+jUFGI/ZJ32yQwLUMCUUlexM1FJvqlg/kgfvPFY2kLPw/rRz2TNCE1MuZrU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
