travis:
  secure:
    BINSTAR_TOKEN: mKsL19xbJkNYsD90cKq098hDHTarKAEsyxMGALZ+ldyoAJmaWN78gbsH5jkq3FqAjZNd0vshuP4tTpKtynLwISPO0cwRV0Aq4Uw1N/6qOkHFfG+SqxX5j/V2tBM83qIHiRqrLrph6UIA6c8xx6g3SPrPXYZJJVhtibYB0hHrWM3nPhwV5PKaR2I51fEots5SYjj3tz/khoJ2a3/ADVPB6O+Q/buEEPUllP6JKxtiCvUBrYfJvI+lNb3MTdkWRadXb3XP2gncw8RkmaYo+xnx6X904Vr4fIZX7R/SRQ+aPYF54ZXD9dFPb5dkYNHgZu+4EMrGvgQuLVEJdq4+txrg2kLib6CpaLF9lrErPU/N0jZZbSUVcSIitkxTxRmnCQaqW3wQZdsnmclHLjHSEP4NdTXZLboc1KPJ2uBYgCYanLuKscvl6QA5deK7U5YycUI3Gp0LIBDHnP1ysh4fJOmHe0v6pJE2KJep/zcv1GC6cimuQCzwmY/qZVYPcaBdPj4+n+zrFgTgAJqpPiNKJe15i69JeKSiq5lj4BG5M7Asa/dv49OMo4u76ALeL1H/FpfZB9u8DL4e8ombPSxb0FMqysDw6kyUNR4xJNPTN/KZLeGN9yTRxJNUKH7Bhc57auSow13FT0ymULo6lK1GFCZSkD129+KwvPoSZpfBcuWp15w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
