travis:
  secure:
    BINSTAR_TOKEN: WBnRLRYnS/b3CMkpijwb7kzVUVS3C6TjtmzRt2N5GX5whqSUsxgoViB/RdYIfxhM5LNvK8bikmbQWxS1HhgDDA8tqm+d5Jp+R+8VbRbGNvkvWEOpLt22ae8ikGhUL9uFC7D0vwxg3cH+wmT7si0cuVY+a0GzXn4HXzIteln1HhLKkROks22mH73cx02FgQBUyXnKo0Bdx9XfLMlIuax4i7AdZNQ55MGUqJrJIJ1mEZv/yzaCh2bQVni8H7iooRuEBBDxcMeSOc55P7g3181ctUV3+op2bCv2g3VxWHAp55rNN+sgMxTe7suKfclOwco54jySTwTWQk7QOuirvoqE67XJq0GdxHNZA4NpTn0RnZ+/AD/krvzulP6tJVpPu3/NdJ1CZd396NKrOEi8hCyUmlKfAX52DiGv7VHp0vfm1eNiS0MK9/RWgQkoT5NGCfSQnPJPrUcxx622vZ+uSrKiMgLQyXG7WgDxb5L3U4QPTgjt39Sdmfool/08aagtF2Sna5vSkIzM+jEZ1vN7f4e40UEgHQCzUUtJOlaiegS6wmaV+43bh0pGsi1afHILHNfVO49ByLRDk9mIfljJlGhzR6ZsTtfzaZZB0II6gOmvWD1D+xwhuLcDWPYaV+yLPolLxD0cgrbnyoheqlo6TtY3SLZd1o08USU92mFMSMRt5EE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
