travis:
  secure:
    BINSTAR_TOKEN: k+t2KsaAaP6FerYK0PEVsDmtFhotWs2NnKQI0VpYiohM49h5FiN5HTZly9Brrv7khd+wAK3EfT+OdqdMOGFl3X7eZR3CpYShhpWvddJ7j4Skbh5HTunCPmVx2ljntaFaMhJI6TBgZDKaE0sceCYbJ9BMB7kgxSYtsd6VrqkUn/VM0OXsapL20I1BMOzDMPcTJCBy2ssJT+JWZZKjGfZCpGlubRKn90wgBJTvm6dUa0Ma+THOYuNBesITwm56DwYGvWthrzljCG//eEzOhuZHdME7Cr6+2h4y/hx/NfwcBxt8zZ4kfaqknsyumsPyG4NLXmn5tkF9a3fzo3IQFVHTuFzD+vBEIkA5J1BAtUG11diSJNUTONkqXujnas+XZBTWDCcvMSN0UN7Frjhzeq2gDXjinLnMolPJIB44zFELex7EIAPobrlOy8K6sPP14vHnzCmPRnZGwHQ4ntvDgTiE2N9HRFLjRUZbDV+oRURb5+uwZyjnxh/cFjyV1LNmYw2Op6Ndb3fiFQ+3E3EGJRVXtlYluy08TimohPaqt3UEyWFJBgHGRohzW7B2CCLf2E9bgSodXeswH6NfQQ5C6cL9OH6G+HpMyEsF3mWXiNP9l+GiGT2KAyRMwO8nU8fiDLvInfRjN0/2CB7DdJro+mv9s1qWJ7nj+zpjLnb6mgAXEaw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
